version: 2

sources:
  - name: sap_adw
    description: "Sources from Adventure Works SAP system"
    schema: sap_adw
    tables:
      - name: address
        description: "Address information for customers, employees, and vendors"
        columns:
          - name: addressid
            description: "Primary key for address records"
            tests:
              - unique
              - not_null
      - name: businessentity
        description: "ID that connects vendors, customers, and employees with address and contact information"
        columns:
          - name: businessentityid
            description: "Primary key for the business entity"
            tests:
              - unique
              - not_null
      - name: businessentityaddress
        description: "Cross-reference table mapping customers, vendors, and employees to their addresses"
        columns:
          - name: businessentityid
            description: "Foreign key to the businessentity table"
            tests:
              - not_null
          - name: addressid
            description: "Foreign key to the address table"
            tests:
              - not_null
      - name: countryregion
        description: "Lookup table containing codes for countries and regions"
        columns:
          - name: countryregioncode
            description: "Primary key for country or region codes"
            tests:
              - unique
              - not_null
      - name: creditcard
        description: "Credit card information"
        columns:
          - name: creditcardid
            description: "Primary key for credit card records"
            tests:
              - unique
              - not_null
      - name: customer
        description: "Customer information"
        columns:
          - name: customerid
            description: "Primary key for customer records"
            tests:
              - unique
              - not_null
      - name: person
        description: "Human beings involved with AdventureWorks: employees, customer contacts, and vendor contacts"
        columns:
          - name: businessentityid
            description: "Foreign key to the businessentity table"
            tests:
              - not_null
      - name: personcreditcard
        description: "Cross-reference table mapping people to their credit card information in the CreditCard table"
        columns:
          - name: businessentityid
            description: "Foreign key to the person table"
            tests:
              - not_null
          - name: creditcardid
            description: "Foreign key to the creditcard table"
            tests:
              - not_null
      - name: product
        description: "Products sold or used in the manufacturing of sold products"
        columns:
          - name: productid
            description: "Primary key for product records"
            tests:
              - unique
              - not_null
      - name: productcategory
        description: "Product categorization"
        columns:
          - name: productcategoryid
            description: "Primary key for product categories"
            tests:
              - unique
              - not_null
      - name: productsubcategory
        description: "Product subcategories"
        columns:
          - name: productsubcategoryid
            description: "Primary key for product subcategories"
            tests:
              - unique
              - not_null
      - name: salesorderdetail
        description: "Individual products associated with a specific sales order"
        columns:
          - name: salesorderdetailid
            description: "Primary key for sales order detail records"
            tests:
              - unique
              - not_null
          - name: salesorderid
            description: "Foreign key to the salesorderheader table"
            tests:
              - not_null
          - name: productid
            description: "Foreign key to the product table"
            tests:
              - not_null
      - name: salesorderheader
        description: "General sales order information"
        columns:
          - name: salesorderid
            description: "Primary key for sales order records"
            tests:
              - unique
              - not_null
      - name: salesorderheadersalesreason
        description: "Cross-reference table mapping sales orders to sales reason codes"
        columns:
          - name: salesorderid
            description: "Foreign key to the salesorderheader table"
            tests:
              - not_null
          - name: salesreasonid
            description: "Foreign key to the salesreason table"
            tests:
              - not_null
      - name: salesreason
        description: "Lookup table of customer purchase reasons"
        columns:
          - name: salesreasonid
            description: "Primary key for sales reasons"
            tests:
              - unique
              - not_null
      - name: stateprovince
        description: "State and province lookup table"
        columns:
          - name: stateprovinceid
            description: "Primary key for state or province records"
            tests:
              - unique
              - not_null
          - name: countryregioncode
            description: "Foreign key for country region table"
            tests:
              - not_null
      - name: store
        description: "Resellers of Adventure Works products"
        columns:
          - name: businessentityid
            description: "Foreign key to the person table"
            tests:
              - not_null
