version: 2

sources:
  - name: sap_adw
    description: Fonte do SAP do Adventure Works
    schema: sap_adw
    tables:
      - name: address
        description: Tabela de endereços
        tests:
          - dbt_expectations.expect_table_column_count_to_equal:
              value: 9
        columns:
          - name: addressid
            description: Id do endereço. Chave primária (PK) da tabela
            data_type: int64
            tests:
              - unique
              - not_null
              - dbt_expectations.expect_column_to_exist

          - name: addressline1
            description: Campo 1 para descrição do endereço
            tests:
              - dbt_expectations.expect_column_to_exist
              - not_null

          - name: addressline2
            description: Campo 2 para descrição do endereço

          - name: city
            description: Cidade do endereço
            tests:
              - dbt_expectations.expect_column_to_exist
              - not_null

          - name: stateprovinceid
            description: Id do estado. Chave estrangeira (FK) da tabela de estados
            data_type: int64
            tests:
              - dbt_expectations.expect_column_to_exist
              - not_null
              - relationships:
                  field: stateprovinceid
                  to: ref('stateprovince')

          - name: spatiallocation
            description: Dados de localização espacial do endereço

          - name: rowguid
            description: Número ROWGUIDCOL que identifica exclusivamente o registro
            tests:
              - unique
              - not_null

          - name: modifieddate
            description: Data e hora em que o registro foi atualizado pela última vez
            tests:
              - not_null
              - dbt_expectations.expect_column_to_exist

      - name: addresstype
        description: Tabela tipos de endereço
        tests:
          - dbt_expectations.expect_table_column_count_to_equal:
              value: 4
        columns:
          - name: addresstypeid
            description: Id do tipo de endereço. Chave primária (PK) da tabela
            data_type: int64
            tests:
              - unique
              - not_null
              - dbt_expectations.expect_column_to_exist
          - name: name
            description: Nome do tipo de endereco
            tests:
              - not_null

      - name: businessentity
        description: Tabela entidade de negócio
      - name: businessentitycontact
        description: Tabela contatos de entidade de negócio
      - name: businessentityaddress
        description: Tabela endereços de entidade de negócio
      - name: stateprovince
        description: Tabela de Estados
        tests:
          - dbt_expectations.expect_table_column_count_to_equal:
              value: 8
        columns:
          - name: stateprovinceid
            description: Id do estado.Chave primária (PK) da tabela
            data_type: int64
            tests:
              - unique
              - not_null
              - dbt_expectations.expect_column_to_exist

          - name: stateprovincecode
            description: Sigla do estado
            tests:
              - dbt_expectations.expect_column_to_exist
              - not_null
          - name: countryregioncode
            description: Código do país. Chave estrangeira (FK) da tabela de países
            data_type: string
            tests:
              - not_null
              - relationships:
                  field: countryregioncode
                  to: ref('countryregion')

          - name: isonlystateprovinceflag
            description: Flag de marcação se o estado é um Estado País
            data_type: boolean

          - name: name
            description: Nome do estado
            tests:
              - dbt_expectations.expect_column_to_exist
              - not_null

          - name: territoryid
            description: Id do território de vendas. Chave estrangeira (FK) da tabela de territórios
            data_type: int64
            tests:
              - dbt_expectations.expect_column_to_exist
              - relationships:
                  field: territoryid
                  to: ref('salesterritory')

          - name: rowguid
            description: Número ROWGUIDCOL que identifica o registro
            tests:
              - unique
              - not_null

          - name: modifieddate
            description: Data e hora que o registro que foi atualizado pela última vez
            tests:
              - not_null
              - dbt_expectations.expect_column_to_exist

      - name: countryregion
        description: Tabela de Países
        tests:
          - dbt_expectations.expect_table_column_count_to_equal:
              value: 3
        columns:
          - name: countryregioncode
            description: Código do país e Chave primária (PK) da tabela
            data_type: string
            tests:
              - unique
              - not_null
              - dbt_expectations.expect_column_to_exist

          - name: name
            description: Nome do país
            tests:
              - not_null
              - dbt_expectations.expect_column_to_exist

          - name: modifieddate
            description: Data e hora que o registro foi atualizado pela última vez
            tests:
              - not_null
              - dbt_expectations.expect_column_to_exist

      - name: department
        description: Tabela de departmento/setor
        tests:
          - not_null
          - dbt_expectations.expect_column_to_exist

      - name: employee
        description: Tabela de funcionarios
        tests:
          - not_null
          - dbt_expectations.expect_table_column_count_to_equal:
              value: 15

      - name: store
        description: Tabela de Lojas
        tests:
          - dbt_expectations.expect_table_column_count_to_equal:
              value: 6

        columns:
          - name: businessentityid
            description: Id da loja. Chave primária (PK) e chave estrangeira (FK) da tabela de entidades
            tests:
              - unique
              - not_null
              - dbt_expectations.expect_column_to_exist
              - relationships:
                  field: businessentityid
                  to: ref('businessentity')

          - name: name
            description: Nome da loja
            tests:
              - not_null
              - dbt_expectations.expect_column_to_exist

          - name: salespersonid
            description: Id do vendedor. Chave estrangeira (FK) da tabela de pessoas
            data_type: int64
            tests:
              - not_null
              - dbt_expectations.expect_column_to_exist
              - relationships:
                  field: businessentityid
                  to: ref('person')

          - name: demographics
            description: dados demográficos da loja

          - name: rowguid
            description: Número ROWGUIDCOL que identifica exclusivamente o registro
            tests:
              - unique
              - not_null

          - name: modifieddate
            description: Data e hora do registro atualizado pela última vez
            tests:
              - not_null
              - dbt_expectations.expect_column_to_exist

      - name: countryregioncurrency
        description: Tabela de moedas dos países
        tests:
          - dbt_expectations.expect_table_column_count_to_equal:
              value: 3
        columns:
          - name: countryregioncode
            description: Código do país. Chave primária (PK) e estrangeira (FK) da tabela de países
            data_type: string
            tests:
              - not_null
              - dbt_expectations.expect_column_to_exist
              - relationships:
                  field: countryregioncode
                  to: ref('countryregion')

      - name: currencycode
        description: Cdigo da moeda. Chave primária (PK) e estrangeira (FK) da tabela de moedas
        data_type: string
        tests:
          - not_null
          - dbt_expectations.expect_column_to_exist
          - relationships:
              field: currencycode
              to: ref('currency')

      - name: salesterritory
        description: Tabela de territórios de vendas
        tests:
          - dbt_expectations.expect_table_column_count_to_equal:
              value: 10
        columns:
          - name: territoryid
            description: Id do território e chave primária (PK) da tabela
            data_type: int64
            tests:
              - unique
              - not_null
              - dbt_expectations.expect_column_to_exist

          - name: name
            description: Nome do territorio
            tests:
              - not_null
              - dbt_expectations.expect_column_to_exist

          - name: countryregioncode
            description: Código do páis do território. Chave estrangeira (FK) da tabela de países
            data_type: string
            tests:
              - not_null
              - dbt_expectations.expect_column_to_exist
              - relationships:
                  field: countryregioncode
                  to: ref('countryregion')

          - name: group
            description: Grupo continental do territorio

          - name: salesytd
            description: Somatorio de vendas por ano e data (YTD)
            data_type: float64

          - name: saleslastyear
            description: Somatorio de vendas do último ano
            data_type: float64

          - name: costytd
            description: Somatorio de custo year to date (YTD)
            data_type: float64

          - name: costlastyear
            description: Somatorio de custo do último ano
            data_type: float64

          - name: modifieddate
            description: Data e hora que o registro foi atualizado pela última vez
            tests:
              - not_null
              - dbt_expectations.expect_column_to_exist

      - name: person
        description: Tabela de pessoas
        tests:
          - dbt_expectations.expect_table_column_count_to_equal:
              value: 13
        columns:
          - name: businessentityid
            description: Id da pessoa. Chave primária (PK) da tabela
            data_type: int64
            tests:
              - unique
              - not_null
              - dbt_expectations.expect_column_to_exist

          - name: persontype
            description:
              Tabela que descreve o tipo de pessoas e a relação com a ADW
              (SC = Logista, IN = Cliente, SP = Vendedor, EM = Empregado, VC = Fornecedor, GC = Geral)
            tests:
              - not_null
              - accepted_values:
                  values:
                    - ["SC", "IN", "SP", "EM", "VC", "GC"]

          - name: namestyle
            description: Estilo de nome (true = E ocidental ou false = Estilo oriental)
            data_type: boolean
            tests:
              - not_null

          - name: title
            description: Referencia ao nome ex = Mr ou Ms

          - name: firstname
            description: primeiro nome da pessoa
            tests:
              - not_null

          - name: middlename
            description: Nome do meio
          - name: lastname
            description: Ultimo nome
          - name: suffix
            description: Sufixo do nome. Ex = Sr. or Jr
          - name: emailpromotion
            description: Tipo de contato por e-mail
              (0 = Não receber,  1 = Somente pela Adw,  2 = Adw e parceiros)
            tests:
              - not_null
              - accepted_values:
                  values: [0, 1, 2]
                  quote: false
          - name: additionalcontactinfo
            description: Informaçoes adicionais de contato sobre a pessoa - formato xml

          - name: demographics
            description: Informações pessoais como hobbies e receitas coletadas on-line. Dados ultilizados para análise de vendas

          - name: rowguid
            description: Número ROWGUIDCOL que identifica o registro
            tests:
              - not_null

          - name: modifieddate
            description: Data e hora em que o registro foi atualizado pela última vez
            tests:
              - not_null
              - dbt_expectations.expect_column_to_exist

      - name: emailaddress
        description: Tabela de e-mails de pessoas
        tests:
        - dbt_expectations.expect_table_column_count_to_equal:
            value: 5
        columns:
        - name: emailaddressid
          description: Id do e-mail. Chave primária (PK) da tabela
          data_type: int64
          tests:
            - unique
            - not_null
            - dbt_expectations.expect_column_to_exist

        - name: businessentityid
          description: Id da pessoa. Chave primária (PK) e estrangeira (FK) da tabela de pessoas
          data_type: int64
          tests:
            - not_null
            - dbt_expectations.expect_column_to_exist
            - relationships:
                field: businessentityid
                to: ref('person')

        - name: emailaddress
          description: Endereço do e-mail
          tests:
            - not_null
            - dbt_expectations.expect_column_to_exist

        - name: rowguid
          description: Número ROWGUIDCOL que identifica exclusivamente o registro
          tests:
            - unique
            - not_null

        - name: modifieddate
          description: Data e hora em que o registro foi atualizado pela última vez
          tests:
            - not_null
            - dbt_expectations.expect_column_to_exist

      - name: product
        description: Tabela de produtos
        tests:
          - dbt_expectations.expect_table_column_count_to_equal:
              value: 25
        columns:
          - name: productid
            description: Id do produto. Chave primária (PK) da tabela
            data_type: int64
            tests:
              - unique
              - not_null
              - dbt_expectations.expect_column_to_exist
