name: "desafiolh_rafaelabertuol"
version: "1.0.0"
config-version: 2
profile: "default"

# Configurations for file paths
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Configuração de modelos
models:
  desafiolh_rafaelabertuol:
    +materialized: view
    marts:
      +schema: marts
      +materialized: table
    staging:
      +schema: stg

seeds:
  desafiolh_rafaelabertuol:
    +schema: sap_adw
    +persist_docs:
      relation: true
      columns: true
