name: "desafiolh_rafaelabertuol"
version: "1.0.0"
config-version: 2
profile: "default"

# Configurations for file paths
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Configuração de modelos
models:
  desafiolh_rafaelabertuol:
    +materialized: view
    marts:
      +materialized: table
      sales:
        dimensions:
        +schema: marts
      facts:
        +schema: marts
      aggregates:
      +schema: marts
    staging:
      +schema: stg
      +materialized: view
      erp:
        +schema:

seeds:
  desafiolh_rafaelabertuol:
    +materialized: seed
    +schema: sap_adw
