name: "desafiolh_rafaelabertuol"
version: "1.0.0"
config-version: 2
profile: "default"

# Configurations for file paths
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Configuração de modelos
models:
  desafiolh_rafaelabertuol:
  marts:
    +materialized: table
    marts:
      +schema: marts
    facts:
      +schema: facts
    dimensions:
      +schema: dimensions
    aggregates:
      +schema: aggregates
  staging:
    +materialized: view

seeds:
  sap_adventure_works:
    +schema: sap_adw
