name: 'aw_data_driven'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  aw_data_driven:
    recursos:
      sap_adw:
        +materialized: table

    comercial:
      +materialized: table

seeds:
  aw_data_driven:
    sap_adventure_works:
      +schema: sap_adw