desafio_final_lh:
  target: dev
  outputs:
    dev:
      dataset: dbt_julio
      type: bigquery
      method: oauth
      project: desafio-final-lh-414719
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      priority: interactive
      threads: 2