default:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: third-anvil-431614-c5
      dataset: sap_adw
      threads: 1
      keyfile: /Users/rafaelabertuol/Desktop/DESAFIO LH/third-anvil-431614-c5-61f879affe61.json
      timeout_seconds: 300
      location: US