version: 2

sources:
  - name: sap_adw
    tables:
      - name: address
        description: "Descrição da tabela address"
      - name: businessentityaddress
        description: "Descrição da tabela address"
        columns:
          - name: addressid
            description: "ID do endereço"
      - name: countryregion
        description: "Descrição da tabela address"
        columns:
          - name: addressid
            description: "ID do endereço"
      - name: stateprovince
        description: "Descrição da tabela address"
        columns:
          - name: addressid
            description: "ID do endereço"
      - name: salesreason
        description: "Descrição da tabela address"
        columns:
          - name: addressid
            description: "ID do endereço"
      - name: salesorderheadersalesreason
        description: "Descrição da tabela address"
        columns:
          - name: addressid
            description: "ID do endereço"
      - name: salesorderdetail
        description: "Descrição da tabela address"
        columns:
          - name: addressid
            description: "ID do endereço"
      - name: salesorderheader
        description: "Descrição da tabela address"
        columns:
          - name: addressid
            description: "ID do endereço"
      - name: person
        description: "Descrição da tabela address"
        columns:
          - name: addressid
            description: "ID do endereço"
      - name: personcreditcard
        description: "Descrição da tabela address"
        columns:
          - name: addressid
            description: "ID do endereço"
      - name: creditcard
        description: "Descrição da tabela address"
        columns:
          - name: addressid
            description: "ID do endereço"
      - name: customer
        description: "Descrição da tabela address"
        columns:
          - name: addressid
            description: "ID do endereço"
      - name: product
        description: "Descrição da tabela address"
        columns:
          - name: addressid
            description: "ID do endereço"
      - name: productsubcategory
        description: "Descrição da tabela address"
        columns:
          - name: addressid
            description: "ID do endereço"
      - name: productcategory
        description: "Descrição da tabela address"
        columns:
          - name: addressid
            description: "ID do endereço"